### ISSUE TITLE
The documentation could make it clear why Substring is preferred over String

### ISSUE THREAD

**Issue by haikusw** [pointfreeco/swift-parsing#112]
The earlier videos make this quite clear but for those who haven't seen those they might not understand why the `[...]` is used and why sometimes the argument to `parse` is `inout` and sometimes not, and why the compiler will present errors for some parsers if you try to pass them a String (they only have Substring and utf8 implementations).

This lack of understanding will increase frustration for new users of this package and reduce adoption as a result.

#111 is a specific instance of an actual typo on this topic.

**Comment by stephencelis** [comment]
@haikusw We've been revamping our docs and now have a dedicated article about string abstractions here: https://pointfreeco.github.io/swift-parsing/main/documentation/parsing/stringabstractions

Does this address your concerns enough to close this issue out?

**Comment by haikusw** [comment]
Sounds promising!  I'll take a look soon and update this as appropriate.

**Comment by stephencelis** [comment]
@haikusw Thanks!

**Comment by haikusw** [comment]
Looks great.  I made a PR with a couple of very minor changes.
