### ISSUE TITLE
Make `ParsingError` public?

### ISSUE THREAD

**Issue by Jeehut** [pointfreeco/swift-parsing#138]
I just started migrating over to the latest version of swift-parsing. While doing that, I had some custom parsers that I wanted to update to the new throwing style. One of my parsers has a `minCharacters` variable and when I can't find that chars, I'd like to throw a `ParsingError`. But when I do, I get an error because `ParsingError` seems to be internal to the library. Is there any reason we shouldn't have access to the `ParsingError` type for our custom parsers? While I could write my own error type, wouldn't it be more convenient if all parsers would throw the same errors?

Here's my custom parser:
```swift
/// A parser that consumes all whitespace characters from the beginning of the input. No output.
struct Whitespaces: Parser {
  let minCharacters: Int

  init(
    minCharacters: Int = 0
  ) {
    self.minCharacters = minCharacters
  }

  func parse(_ input: inout Substring) throws {
    let foundWhitespaces = input.prefix { char in
      char == " " || char == "\n" || char == "\r" || char == "\t"
    }

    guard foundWhitespaces.count >= minCharacters else {
      throw ParsingError.expectedInput("\(minCharacters) whitespaces", at: input)
      // => ERROR: Cannot find 'ParsingError' in scope
    }

    input.removeFirst(foundWhitespaces.count)
  }
}

```

**Comment by stephencelis** [comment]
@Jeehut I'm going to convert this to a discussion since it's not a bug but an intentionally internal type while its APIs become more fully baked.
