### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nashysolutions** [pointfreeco/swift-parsing#312]
This might be a typo?

"...print the structure data back into structured data"

![image](https://github.com/pointfreeco/swift-parsing/assets/64097812/7720c5b7-1250-4fd4-8d34-064660189732)

**Comment by mbrandonw** [comment]
Thanks, fixed [here](https://github.com/pointfreeco/pointfreeco/blob/main/Sources/Transcripts/Collections/Tours.swift).
