### ISSUE TITLE
Consider putting more parsers in the Parsers namespace

### ISSUE THREAD

**Issue by mayoff** [pointfreeco/swift-parsing#4]
This is just a humble suggestion from a fan.

I see that you have an `public enum Parsers { }` to use as a namespace, like Combine does with the `Publishers` type. But you've still defined several parser types (like `Lazy`, `Prefix`, and `First`) at module scope, to make it more convenient to use them. But this is likely, particularly in the case of `Lazy`, to conflict with names from other modules.

Here's an alternative to consider: put all the parser types in the `Parsers` namespace. Then define a protocol `ParserUsing` that “imports” those names as type aliases. Example:

```
// ---- ParserUsing.swift
public protocol ParserUsing { }

extension Parsers: ParserUsing { }

// ---- Parser.swift
public protocol Parser: ParserUsing {
...
}

// ---- First.swift
...
extension ParserUsing {
    public typealias First = Parsers.First
}

// ---- Lazy.swift
...
extension ParserUsing {
    public typealias Lazy = Parsers.Lazy
}

// ---- Prefix.swift
...
extension ParserUsing {
    public typealias Prefix = Parsers.Prefix
}
```

Since `Parser` is a subprotocol of `ParserUsing`, every `Parser` automatically conforms to `ParserUsing` and has access to the type aliases. And since `Parsers` conforms to `ParserUsing`, the same is true in every extension of `Parsers`.

Further, any type that builds a parser can add a conformance to `ParserUsing` to import the type aliases. Example:

```
final class PrefixTests: XCTestCase, ParserUsing {
...
}
```

**Comment by mbrandonw** [comment]
Hey @mayoff, thanks for bringing this up! It's actually something @stephencelis and I discussed quite a bit before open sourcing. We're still not sure where to draw the line. We're kinda following Combine's lead here.

Your suggestion is interesting, but unfortunately would only work when implementing a parser by conforming a type to the `Parser` protocol. If you were to use the `Prefix` parser at the top level (as we do in our benchmark case studies) you would have to use it as `Parsers.Prefix`, which would be pretty verbose.

We're happy to discuss this more, but it might be better to do so in the [discussions](https://github.com/pointfreeco/swift-parsing/discussions) tab. This is our first time using this GitHub feature.
