### ISSUE TITLE
Add `tryParse` to reuse existing optional init

### ISSUE THREAD

**Issue by surajbarkale** [pointfreeco/swift-parsing#46]
In cases like `RawRepresentable`, the logic for parsing is already present in the optional init function. I am using following `tryParse` helper (copied over from `map`). Would this be considered for inclusion in the library?

```swift
import Parsing

extension Parser {
  /// Returns a parser that uses the given closure to perform final parsing of the output of this parser.
  ///
  /// - Parameter transform: A closure that transforms values of this parser's output. Returning nil if transform fails.
  /// - Returns: A parser of transformed outputs.
  @inlinable
  public func tryParse<NewOutput>(
    _ parseFn: @escaping (Output) -> NewOutput?
  ) -> Parsers.TryParse<Self, NewOutput> {
    .init(upstream: self, parseFn: parseFn)
  }
}

extension Parsers {
  /// A parser that parses the output of another parser with a given closure.
  public struct TryParse<Upstream, Output>: Parser where Upstream: Parser {
    /// The parser from which this parser receives output.
    public let upstream: Upstream

    /// The closure that parses output from the upstream parser.
    public let parseFn: (Upstream.Output) -> Output?

    @inlinable
    public init(upstream: Upstream, parseFn: @escaping (Upstream.Output) -> Output?) {
      self.upstream = upstream
      self.parseFn = parseFn
    }

    @inlinable
    @inline(__always)
    public func parse(_ input: inout Upstream.Input) -> Output? {
        self.upstream.parse(&input).flatMap(self.parseFn)
    }
  }
}
```

**Comment by stephencelis** [comment]
Hi @surajbarkale! Thanks for starting a discussion. This parser looks a lot like `Parser.compactMap`:

https://github.com/pointfreeco/swift-parsing/blob/625c1f23eb4902b5742a94e7d7a47d068d2bf68d/Sources/Parsing/Parsers/CompactMap.swift

I think them main difference is that `compactMap` will backtrack if parsing fails. Does `compactMap` work for you in your use case?

**Comment by surajbarkale** [comment]
I explicitly do not want backtracking behaviour. Consider a use case where one of the columns in CSV file is mapped to an enum. When parsing a line, I want the whole line to fail if the enum column contains invalid value. This can be achieved by using `.orElse` chaining in parser. However, then I have to remember to change the parser when enum changes.

The `tryParse` allows me to say extract this string and parse using this external function to get a real data type. Another use case is parsing delimited UUID's using `UUID.init?(uuidString:)` instead of writing explicit UUID parser.

**Comment by stephencelis** [comment]
@surajbarkale I'm not sure I understand. Can you provide a working code sample that shows the problem? A test case that shows `tryParse` succeeding where `compactMap` fails would help me better understand.

**Comment by surajbarkale** [comment]
After running some examples I realized that the end result of `compactMap` is the same. So this extension is not needed.
